// angular-sample-app/src/app/components/routing/routing.component.ts
import { Component, OnDestroy, OnInit } from "@angular/core";
import * as TrimbleMaps from "@trimblemaps/trimblemaps-js";
import * as _ from "lodash";
import { hazardousTypes } from "src/app/models/hazardousTypes";
import { routeTypes } from "src/app/models/routeType";
import { SingleSearchLocation } from "src/app/models/searchResponse";
import { MapRegion } from "src/app/models/trimbleMaps";
import { vehicleType } from "src/app/models/vehicleType";
import { MapService } from "src/app/services/map.service";
import { SearchService } from "src/app/services/search.service";
import {
  AbstractControl,
  FormBuilder,
  FormControl,
  FormGroup,
  Validators,
} from "@angular/forms";
import { SubscriptionManager } from "src/app/utils/subscription-manager";
import { ModalService } from "../modal.service";
import { autoDescription } from "src/app/utils/autoDescription";
import { combineLatest, debounceTime, distinctUntilChanged } from "rxjs";
import { MileageReportResponse } from "src/app/models/mileageReport";
import { DetailReportResponse } from "src/app/models/detailedReport";
import { DirectionsReportResponse } from "src/app/models/directionReport";
import { StateReportResponse } from "src/app/models/stateReport";
import { RoadTypeReport } from "src/app/models/roadTypeReport";
import { LicenseFeature } from "src/app/models/license";
import { constants } from "src/app/utils/constants";
import { RouteLocation } from "src/app/models/routeLocation";
import { layerSpecificLocation } from "src/app/utils/layerSpecificLocation";

export interface StopIcon {
  stopType: string;
  shortAddress: string;
}
@Component({
  selector: "app-routing",
  templateUrl: "./routing.component.html",
  styleUrls: ["./routing.component.scss"],
})
export class RoutingComponent implements OnInit, OnDestroy {
  region!: MapRegion;
  vehicleTypes: any = [];
  routeTypes = routeTypes;
  hazardousTypes = hazardousTypes;
  dataVersion!: MapRegion;
  showReport = false;
  routeReports!: [
    MileageReportResponse,
    DetailReportResponse,
    DirectionsReportResponse,
    StateReportResponse,
    RoadTypeReport
  ];
  showReportsBtn = false;
  showRouteBtn = false;
  showLoading!: boolean;
  hasError!: boolean;
  noData!: boolean;
  private sm = new SubscriptionManager();
  isNA = false;
  vehicleDescription!: string;
  routeSettingForm!: FormGroup;
  license!: LicenseFeature;
  unlicensed_msg = constants.UNLICENSED_MSG;
  stopsList: string[] = [];

  constructor(
    private searchService: SearchService,
    private mapService: MapService,
    private modalService: ModalService,
    private formBuilder: FormBuilder
  ) {}
  ngOnInit() {
    this.routeLocationInput = new FormControl("", [
      Validators.required,
      Validators.minLength(1),
      Validators.pattern("^[a-zA-Z]+$"),
    ]);

    this.routeSettingForm = this.formBuilder.group({
      vehicleType: "",
      routeType: TrimbleMaps.Common.RouteType.PRACTICAL,
      avoidTolls: false,
      routingHighwayOnly: false,
      bordersOpen: false,
      hazMat: TrimbleMaps.Common.HazMatType.NONE,
    });

    this.sm.add(
      this.mapService.currentRegion$.subscribe((region) => {
        this.region = region;
        this.dataVersion = region;
        this.isNA = region === TrimbleMaps.Common.Region.NA;
      })
    );
    this.sm.add(
      combineLatest([
        this.mapService.currentRegion$,
        this.routeSettingFormControls["vehicleType"].valueChanges,
      ]).subscribe(([region, vehicleType]) => {
        this.vehicleDescription = autoDescription(region, vehicleType);
        if (vehicleType === TrimbleMaps.Common.VehicleType.AUTOMOBILE) {
          this.routeTypes = [
            {
              displayName: "Fastest",
              value: TrimbleMaps.Common.RouteType.FASTEST,
            },
          ];
          this.routeSettingFormControls["routeType"].setValue(
            TrimbleMaps.Common.RouteType.FASTEST
          );
        } else {
          this.routeTypes = [
            {
              displayName: "Practical",
              value: TrimbleMaps.Common.RouteType.PRACTICAL,
            },
            {
              displayName: "Shortest",
              value: TrimbleMaps.Common.RouteType.SHORTEST,
            },
          ];
          this.routeSettingFormControls["routeType"].setValue(
            TrimbleMaps.Common.RouteType.PRACTICAL
          );
        }
      })
    );
    this.sm.add(
      this.routeSettingForm.valueChanges.subscribe(() => {
        this.onChangeEvent();
      })
    );
    this.routeSettingFormControls["vehicleType"].setValue(
      TrimbleMaps.Common.VehicleType.AUTOMOBILE
    );
    this.sm.add(
      this.routeLocationInput.valueChanges.subscribe((val) => {
        if (val) {
          this.showLoading = true;
          this.searchService
            .search(this.routeLocationInput.value, this.region)
            .pipe(
              debounceTime(250), // wait 500ms after the last keystroke
              distinctUntilChanged() // only emit if value actually changed
            )
            .subscribe({
              next: (location) => {
                this.locationList = location;
                this.showLoading = false;
                if (location && location.length > 0) {
                  this.hasError = false;
                  this.noData = false;
                } else {
                  this.noData = true;
                }
              },
              error: () => {
                this.showLoading = false;
                this.hasError = true;
                this.locationList = [];
              },
            });
        } else {
          this.locationList = [];
        }
      })
    );

    this.sm.add(
      this.mapService.license$.subscribe((license) => {
        this.license = license;
        this.vehicleTypes = vehicleType;
      })
    );
    this.sm.add(
      this.mapService.mapRouteComplete$.subscribe((complete) => {
        if (complete) {
          this.modalService.hideLoading();
          this.showReportsBtn = true;
        }
      }),
      this.mapService.mapRouteError$.subscribe((error) => {
        if (error) {
          this.showReportsBtn = false;
          this.modalService.hideLoading();
        }
      })
    );
  }
  locationList: SingleSearchLocation[] | undefined = [];
  routeLocationInput!: FormControl;
  routeLocations: RouteLocation[] = [];
  locationListContents: StopIcon[] = [];
  lan!: TrimbleMaps.LngLat;
  disableInput = false;
  placeholderText = "Enter Location...";

  clearLocations() {
    this.routeLocationInput.setValue("");
    this.locationListContents = [];
    this.stopsList = [];
    this.disableInput = false;
    this.placeholderText = "Enter Location...";
    this.routeLocations = [];
    this.showReportsBtn = false;
    this.showRouteBtn = false;
    this.mapService.removeRoutes();
    this.mapService.removeStops();
    const mapLocation = layerSpecificLocation(this.mapService.getRegion());
    this.mapService.changeMapLocation(mapLocation);
  }

  locationSelect(location: SingleSearchLocation) {
    if (location.ShortString) {
      this.stopsList.push(location.ShortString);
    }
    if (!_.isUndefined(location.Coords)) {
      this.routeLocations.push({
        coord: new TrimbleMaps.LngLat(location.Coords.Lon, location.Coords.Lat),
        address: location.ShortString,
      });
      this.locationListContents = [];
      this.mapService.centerOnMap([location.Coords.Lon, location.Coords.Lat]);
      this.mapService.addMarker(this.routeLocations);
    }
    if (this.routeLocations.length > 2) {
      this.disableInput = true;
      this.placeholderText =
        "This sample app is limited to a max of three stops";
    }
    if (this.routeLocations.length > 1) {
      this.showRouteBtn = true;
    }
    this.locationListContents = this.stopsList.map((s, index) =>
      this.transformStops(s, index, this.stopsList)
    );
    this.routeLocationInput.setValue("");
    this.locationList = [];
  }
  transformStops(
    shortAddress: string,
    index: number,
    stopState: string[]
  ): StopIcon {
    let stopType = "S";
    if (index === 0) {
      stopType = "O";
    } else if (index === stopState.length - 1) {
      stopType = "D";
    }
    return {
      stopType,
      shortAddress,
    };
  }
  get routeSettingFormControls(): { [key: string]: AbstractControl } {
    return this.routeSettingForm.controls;
  }
  addRouteLayer() {
    //Geocodes the origin and destination, and if they are valid will add the route to the map.
    this.mapService.removeRoutes();
    this.modalService.addLoading("Loading Route");
    let tolls;
    if (this.routeSettingFormControls["avoidTolls"].value) {
      tolls = TrimbleMaps.Common.TollRoadsType.AVOID_IF_POSSIBLE;
    } else {
      tolls = TrimbleMaps.Common.TollRoadsType.USE;
    }
    const stops = this.routeLocations.map((location) => location.coord);
    this.mapService.createRoute(
      stops,
      this.routeSettingFormControls["routeType"].value,
      this.routeSettingFormControls["vehicleType"].value,
      this.routeSettingFormControls["routingHighwayOnly"].value,
      tolls,
      this.routeSettingFormControls["bordersOpen"].value,
      this.routeSettingFormControls["hazMat"].value,
      false,
      this.dataVersion,
      1
    );
  }

  onChangeEvent() {
    this.showReportsBtn = false;
    this.mapService.removeRoutes();
  }

  showReports() {
    this.modalService.showReports(this.routeReports, this.dataVersion);
  }

  ngOnDestroy() {
    this.sm.unsubscribe();
  }
}

<div class="modus-panel panel-lg h-100 shadow">
  <div class="panel-header">
    <h4>Locations</h4>
  </div>
  <div class="mb-2 p-2">
    <div id="locationList" class="p-2">
      <table class="w-100">
        <!-- Route Stops -->
        <tr class="route-stop-row">
          <th colspan="2"></th>
          <th class="route-stop-detail-cell">
          </th>
        </tr>
        <!-- Route Stops -->
        <tr class="route-stop-row" *ngFor="let stop of locationListContents; let stopIndex = index">
          <td class="route-stop-icon-cell">
            <span class="route-stop-line" *ngIf="locationListContents.length > 0" [ngClass]="{
              top: locationListContents.length > 1 && stopIndex === 0,
              bottom: stopIndex === locationListContents.length - 1 && stopIndex !== 0,
              middle: stopIndex !== 0 && stopIndex !== locationListContents.length - 1
            }"></span>
            <span class="route-stop-circle " *ngIf="stop.stopType === 'O' || stop.stopType === 'D'" [ngClass]="{
            origin: stop.stopType === 'O',
            destination: stop.stopType === 'D'
          }"></span>
            <span class="route-stop-number routeColor" *ngIf="stop.stopType === 'S'">{{ stopIndex }}</span>
          </td>
          <td class="route-stop-address">
            <div class="font-weight-bolder">
              {{ stop.shortAddress}}
            </div>

          </td>



        </tr>


      </table>

      <button type="button" class="btn btn-primary" id="clearLocationsBtn" (click)="clearLocations()"
        *ngIf="locationListContents?.length !== 0">
        Clear
      </button>
    </div>

    <div class="mb-2 p-2">
      <label class="col-form-label fw-normal" for="routeLocationInput">Location Selection</label>
      <input class="form-control" id="routeLocationInput" [placeholder]="placeholderText" [readonly]="disableInput"
        [formControl]="routeLocationInput" [ngClass]="{ 'is-invalid': hasError }" />
      <div class="invalid-feedback" *ngIf="routeLocationInput.touched && routeLocationInput.errors">
        <p *ngIf="routeLocationInput.errors['required']">
          Please enter location
        </p>
        <p *ngIf="routeLocationInput.errors['minlength']">
          Name should be more than 3 characters.
        </p>
      </div>
      <div class="invalid-feedback" id="singleSearchErrorText">
        <p *ngIf="
            (routeLocationInput.errors &&
              routeLocationInput.errors['pattern']) ||
            hasError
          ">
          Single search error invalid input
        </p>
        <span *ngIf="noData">No results found</span>
      </div>
    </div>

    <div class="p-2">
      <div id="singleSearchLoading" *ngIf="showLoading">
        <div>
          <div class="text-center text-primary">
            <div class="spinner-border"></div>
            <div class="h3 text-primary mt-3">Loading...</div>
          </div>
        </div>
      </div>
      <div id="locationSelectionDiv">
        <ul class="list-group list-group-condensed" id="locationSelection">
          <li class="list-group-item" *ngFor="let location of locationList; let i = index"
            (click)="locationSelect(location)" (keyup)="locationSelect(location)" tabindex="0">
            {{ location?.ShortString }}
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div panel-header class="border-bottom align-items-center" bg-transparent style="margin-top: 10px">
    <h5 class="px-2 text-center">Route Settings</h5>
  </div>

  <div class="panel-body flex-fill p-2 overflow-auto">
    <form [formGroup]="routeSettingForm">
      <div class="mb-2">
        <label class="col-form-label fw-normal" for="vehicleType"><b>Vehicle Type</b></label>
        <ng-container *ngIf="license.vehicleDimension">
          <p style="font-size: 0.9em">
            Sample app uses pre-defined vehicle profiles, but SDK does support full
            vehicle dimension customization.<br /><br />
            <b>Current vehicle dimensions:</b>
          </p>
          <p id="profileDimensions" [innerHTML]="vehicleDescription" style="font-size: 0.9em"></p>
        </ng-container>
        <select class="form-select" id="vehicleType" formControlName="vehicleType">
          <option *ngFor="let vehicle of vehicleTypes" [ngValue]="vehicle.value"
            [disabled]="!license.truckRouting && vehicle.requiresLicense">
            {{
            !license.truckRouting && vehicle.requiresLicense
            ? vehicle.displayName + " (Unlicensed Feature)"
            : vehicle.displayName
            }}
          </option>
        </select>
      </div>
      <div class="mb-2">
        <label class="col-form-label fw-normal" for="routeType"><b>Route Type</b></label>
        <p style="font-size: 0.9em">
          <b>Practical</b>: Most logical route we believe a driver would take.
          Balances distance, duration, number of turns and road
          classifications.<br />
          <b>Shortest</b>: Uses shortest distance from stop to stop.<br />
          <b>Fastest</b>: Uses the fastest duration from stop to stop.
        </p>
        <select class="form-select" id="routeType" formControlName="routeType">
          <option *ngFor="let route of routeTypes" [ngValue]="route.value">
            {{ route.displayName }}
          </option>
        </select>
      </div>
      <div class="mb-2">
        <div class="mb-2" id="highwayOnlyForm" *ngIf="isNA">
          <div class="form-check form-switch">
            <input type="checkbox" class="form-check-input" role="switch" id="routingHighwayOnly"
              formControlName="routingHighwayOnly" />
            <label class="form-check-label" for="routingHighwayOnly">Highway Routing Only</label>
            <p class="small ms-1">
              Use street data or only highways for routing.
            </p>
          </div>
        </div>

        <div class="mb-2">
          <div class="form-check form-switch" [ngClass]="{ disabled: !license.tolls }">
            <input type="checkbox" class="form-check-input" role="switch" id="avoidTolls"
              formControlName="avoidTolls" />
            <label class="form-check-label" for="avoidTolls">Avoid Tolls</label>
            <p class="small ms-1">
              Allow use of tolls plazas or avoid if possible.
            </p>
          </div>
          <app-tooltip [showTooltip]="!license.tolls"></app-tooltip>
        </div>

        <div class="mb-2">
          <div class="form-check form-switch">
            <input type="checkbox" class="form-check-input" role="switch" id="bordersOpen"
              formControlName="bordersOpen" />
            <label class="form-check-label" for="bordersOpen">Borders Open</label>
            <p class="small ms-1">
              Open/close international borders if possible.
            </p>
          </div>
          <br />
        </div>
      </div>
      <div class="mb-2">
        <label class="d-inline col-form-label fw-normal" for="hazMat"><b>Hazardous Materials</b></label>
        <app-tooltip [showTooltip]="!license.hazmat"></app-tooltip>

        <p class="small">Include hazardous materials for transit.</p>
        <select class="form-select" id="hazMat" formControlName="hazMat"
          [ngClass]="{ disabled: !license.hazmat }">
          <option *ngFor="let hazardous of hazardousTypes" [ngValue]="hazardous.value">
            {{ hazardous.displayName }}
          </option>
        </select>
      </div>

      <div class="float-end mt-2">
        <button type="button" class="btn btn-primary" id="routeBtn" [ngClass]="{ disabled: !showRouteBtn }"
          (click)="addRouteLayer()">
          Route
        </button>
        <button type="button" *ngIf="showReportsBtn" class="btn btn-primary ms-2" id="reportsBtn"
          [disabled]="!license.premiumReports" (click)="showReports()">
          Show Reports
        </button>
        <app-tooltip [showTooltip]="
            !license.premiumReports && showReportsBtn
          "></app-tooltip>
      </div>
    </form>
  </div>
</div>

// react-js-sample-app/src/components/Routing/Routing.jsx
import React, { useEffect, useState } from "react";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";
import { useForm } from "react-hook-form";
import { vehicleType, routeTypes, hazardousTypes } from "../../Utils/routing";
import * as TrimbleMaps from "@trimblemaps/trimblemaps-js";
import "./Routing.scss";
import { useMapContext } from "../../context/mapContext";
import { useOutletContext } from "react-router-dom";
import SearchInput from "./SearchInput";
import ShowReports from "./Reports";
import AutoDescription from "./AutoDescription";
import CustomTooltip from "../ToolTip/CustomTooltip";
import LoadingModal from "../sharedComponents/LoadingModal";

function Routing() {
  const { register } = useForm({
    mode: "onChange",
  });
  const [routeLocations, setRouteLocation] = useState([]);
  const { licensedFeature, setShowToast, setMessage } = useOutletContext();
  const { map, mapService } = useMapContext();
  const [showReportsBtn, setShowReportsBtn] = useState(false);
  const [disabledRouteBtn, setDisabledRouteBtn] = useState(true);
  const [vehicleTypes, setVehicleTypes] = useState(vehicleType);
  const region = map.getRegion();
  // eslint-disable-next-line no-unused-vars
  const [mapRoute, setMapRoute] = useState(undefined);
  const [reports, setReports] = useState(undefined);
  const [routeFormData, setRouteFormData] = useState({
    vehicleType: TrimbleMaps.Common.VehicleType.TRUCK,
    routeType: TrimbleMaps.Common.RouteType.PRACTICAL,
    routingHighwayOnly: false,
    avoidTolls: false,
    bordersOpen: false,
    hazMat: TrimbleMaps.Common.HazMatType.NONE,
  });
  const [routeTypeOptions, setRouteTypeOptions] = useState(routeTypes);
  const [show, setShow] = useState(false);

  useEffect(() => {
    if (!licensedFeature.truckRouting) {
      setVehicleTypes([
        {
          displayName: "Truck",
          value: TrimbleMaps.Common.VehicleType.TRUCK,
          requireLicense: true,
        },
        {
          displayName: "Light Truck",
          value: TrimbleMaps.Common.VehicleType.LIGHT_TRUCK,
          requireLicense: false,
        },
        {
          displayName: "Auto",
          value: TrimbleMaps.Common.VehicleType.AUTOMOBILE,
          requireLicense: false,
        },
      ]);
      setRouteFormData((prev) => ({
        ...prev,
        vehicleType: TrimbleMaps.Common.VehicleType.AUTOMOBILE,
      }));
    }
  }, [licensedFeature]);

  const addRouteLayer = () => {
    setShow(true);
    mapService.removeRoutes();
    let tolls;
    if (routeFormData.avoidTolls) {
      tolls = TrimbleMaps.Common.TollRoadsType.AVOID_IF_POSSIBLE;
    } else {
      tolls = TrimbleMaps.Common.TollRoadsType.USE;
    }
    const stops = routeLocations.map((location) => location.coord);
    mapService.createRoute(
      map,
      stops,
      routeFormData.routeType,
      routeFormData.vehicleType,
      routeFormData.routingHighwayOnly,
      tolls,
      routeFormData.bordersOpen,
      routeFormData.hazMat,
      false,
      region,
      1
    );

    mapService.mapRoute.on("report", (reports) => {
      setReports(reports);
      setMapRoute(mapService.mapRoute);
      setShowReportsBtn(true);
    });
    mapService.mapRoute.on("route", () => {
      setShow(false);
    });
    mapService.mapRoute.on("error", () => {
      setShow(false);
      setShowToast(true);
      setMessage({
        type: "error",
        text: "Error in creating route",
      });
    });
  };

  const handleRouteLocationsChange = (locations) => {
    setRouteLocation(locations);
    if (locations.length > 1) {
      setDisabledRouteBtn(false);
    } else {
      setDisabledRouteBtn(true);
      setShowReportsBtn(false);
    }
  };
  const onChangeEvent = (input, e) => {
    if (input === "switch") {
      setRouteFormData((prev) => ({
        ...prev,
        [e.target.id]: e.target.checked,
      }));
    } else {
      setRouteFormData((prev) => ({
        ...prev,
        [e.target.id]: Number(e.target.value),
      }));
    }
  };
  const onVehicleTypeChange = (e, input, callback) => {
    if (Number(e.target.value) === TrimbleMaps.Common.VehicleType.AUTOMOBILE) {
      setRouteTypeOptions([
        { displayName: "Fastest", value: TrimbleMaps.Common.RouteType.FASTEST },
      ]);
    } else {
      setRouteTypeOptions(routeTypes);
    }
    callback(input, e);
  };

  return (
    <div>
      <div className="modus-panel panel-lg h-100 shadow">
        <div className="panel-header">
          <h4>Locations</h4>
        </div>
        <SearchInput
          routeLocations={routeLocations}
          setRouteLocation={handleRouteLocationsChange}
          setShowToast={setShowToast}
        />
        <div className="panel-header bg-transparent border-bottom align-items-center">
          <h5 className="px-2 text-center">Route Settings</h5>
        </div>
        <div className="panel-body flex-fill p-2 overflow-auto">
          <form>
            <div className=" ">
              <div className="mb-3">
                <label
                  htmlFor="vehicleType"
                  className="col-form-label fw-normal">
                  <b>Vehicle Type</b>
                </label>
                {licensedFeature.vehicleDimension ? (
                  <div>
                    <p className="p-font-size">
                      Sample app uses pre-defined vehicle profiles, but SDK does
                      support full vehicle dimension customization.
                      <br />
                      <br />
                      <b>Current vehicle dimensions:</b>
                    </p>
                    <AutoDescription
                      region={region}
                      vehicleType={routeFormData.vehicleType}></AutoDescription>
                  </div>
                ) : null}
                <Form.Group controlId="vehicleType">
                  <Form.Control
                    as="select"
                    className="form-select"
                    value={routeFormData.vehicleType}
                    {...register("vehicleType")}
                    // eslint-disable-next-line no-unused-vars
                    onChange={(e, _input, callback) =>
                      onVehicleTypeChange(e, "select", onChangeEvent)
                    }>
                    {vehicleTypes.map((vehicle) => (
                      <option
                        key={vehicle.value}
                        value={vehicle.value}
                        disabled={vehicle.requireLicense}>
                        {vehicle.requireLicense
                          ? vehicle.displayName + " (Unlicensed Feature)"
                          : vehicle.displayName}
                      </option>
                    ))}
                  </Form.Control>
                </Form.Group>
              </div>
              <Form.Group controlId="routeType">
                <Form.Label>Route Type</Form.Label>
                <p className="p-font-size">
                  <b>Practical</b>: Most logical route we believe a driver would
                  take. Balances distance, duration, number of turns and road
                  classifications.
                  <br />
                  <b>Shortest</b>: Uses shortest distance from stop to stop.
                  <br />
                  <b>Fastest</b>: Uses the fastest duration from stop to stop.
                </p>
                <Form.Control
                  as="select"
                  className="form-select"
                  value={routeFormData.routeType}
                  {...register("routeType")}
                  onChange={(e) => onChangeEvent("select", e)}>
                  {routeTypeOptions.map((route) => (
                    <option key={route.value} value={route.value}>
                      {route.displayName}
                    </option>
                  ))}
                </Form.Control>
              </Form.Group>
              {region === TrimbleMaps.Common.Region.NA ? (
                <Form.Group controlId="routingHighwayOnly">
                  <Form.Check
                    type="switch"
                    id="routingHighwayOnly"
                    label="Highway Routing Only "
                    {...register("routingHighwayOnly")}
                    onChange={(e) => onChangeEvent("switch", e)}
                    defaultChecked={false}
                  />
                  <p className="p-font-size">
                    Use street data or only highways for routing.
                  </p>
                </Form.Group>
              ) : null}

              <Form.Group controlId="avoidTolls">
                <Form.Check
                  type="switch"
                  id="avoidTolls"
                  label="Avoid Tolls"
                  {...register("avoidTolls")}
                  onChange={(e) => onChangeEvent("switch", e)}
                  disabled={!licensedFeature.tolls}
                />
                <p
                  className={
                    !licensedFeature.tolls
                      ? "p-font-size d-inline disabled"
                      : "p-font-size d-inline"
                  }
                  disabled={!licensedFeature.tolls}>
                  Allow use of tolls plazas or avoid if possible.
                </p>
                <CustomTooltip
                  showToolTip={!licensedFeature.tolls}></CustomTooltip>
              </Form.Group>

              <Form.Group controlId="bordersOpen">
                <Form.Check
                  type="switch"
                  id="bordersOpen"
                  label="Borders Open"
                  {...register("bordersOpen")}
                  onChange={(e) => onChangeEvent("switch", e)}
                />
                <p className="p-font-size">
                  Open/close international borders if possible.
                </p>
              </Form.Group>

              <Form.Group controlId="hazMat">
                <Form.Label>Hazardous Materials</Form.Label>
                <CustomTooltip
                  showToolTip={!licensedFeature.hazmat}></CustomTooltip>
                <Form.Control
                  as="select"
                  className="form-select"
                  value={routeFormData.hazMat}
                  {...register("hazMat")}
                  onChange={(e) => onChangeEvent("select", e)}
                  disabled={!licensedFeature.hazmat}>
                  {hazardousTypes.map((hazardousType) => (
                    <option
                      key={hazardousType.value}
                      value={hazardousType.value}>
                      {hazardousType.displayName}
                    </option>
                  ))}
                </Form.Control>
                <p className="p-font-size">
                  Include hazardous materials for transit.
                </p>
              </Form.Group>
            </div>

            <div className="float-end">
              <Button
                type="button"
                className="btn btn-primary"
                id="routeBtn"
                onClick={addRouteLayer}
                disabled={disabledRouteBtn}>
                Route
              </Button>
              {showReportsBtn ? (
                <ShowReports
                  reports={reports}
                  disableBtn={showReportsBtn && !licensedFeature.premiumReports}
                />
              ) : null}
            </div>
          </form>
        </div>
      </div>
      <LoadingModal
        setShow={setShow}
        show={show}
        loadingText={"Loading..."}></LoadingModal>
    </div>
  );
}

export default Routing;
