// angular-sample-app/src/app/components/get-api-key-modal/get-api-key-modal.component.ts
import { Component, EventEmitter, OnInit, Output } from "@angular/core";
import { MapService } from "src/app/services/map.service";
import { constants } from "src/app/utils/constants";

@Component({
  standalone: false,
  selector: "app-get-api-key-modal",
  templateUrl: "./get-api-key-modal.component.html",
  styleUrls: ["./get-api-key-modal.component.scss"],
})
export class GetApiKeyModalComponent implements OnInit {
  apiKey!: string;
  @Output() apiKey$ = new EventEmitter<string>();
  apiError!: boolean;
  apiError_msg = constants.API_ERROR_MSG;
  constructor(private mapService: MapService) {}
  ngOnInit() {
    this.mapService.apiKeyError$.subscribe((error) => {
      if (error) {
        this.apiError = true;
      }
    });
  }
  submit() {
    this.apiKey$.emit(this.apiKey);
  }
}

<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="modal-title">Authentication</h5>
  </div>
  <div class="modal-body">
    <div class="alert alert-danger alert-dismissible fade show" role="alert" *ngIf="apiError">
      {{apiError_msg}}

    </div>
    <label for="keyInput" class="form-label"><span>Trimble Maps SDK API Key</span><span
        class="required">*</span></label>
    <input class="form-control" id="keyInput" placeholder="API Key" maxlength="32" minlength="32" type="password" required [(ngModel)]="apiKey" />
    <!-- eslint-disable-next-line @angular-eslint/template/elements-content -->
    <div class="fst-italic mt-1">To gain access you must have an API key. Please contact your Trimble Maps
      representative
      or
      our <a
        href="https://maps.trimble.com/contact/"
        target="_blank" rel="noopener">Sales team</a> for more information.</div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" (click)="submit()">
      Submit
    </button>
  </div>
</div>

// react-js-demo/src/components/sharedComponents/GetAPIKeyModal.jsx
import React, { useEffect, useRef } from "react";
import Modal from "react-bootstrap/Modal";
import Button from "react-bootstrap/Button";
import Alert from "react-bootstrap/Alert";
import useToken from "../../hooks/useToken";
import * as _ from "lodash";
import { constants } from "../../Utils/constants";

function GetAPIKeyModal(props) {
  const { showModal, setShowModal, apiKey, setApiKey, setLicensedFeature } =
    props;

  let { jwtToken, error } = useToken(apiKey);
  useEffect(() => {
    if (!_.isEmpty(jwtToken)) {
      setLicensedFeature(jwtToken);
      setShowModal(false);
    }
  }, [jwtToken, error]);

  const submit = () => {
    setApiKey(inputRef.current.value);
  };
  const inputRef = useRef();
  return (
    <Modal
      show={showModal}
      onHide={() => setShowModal(false)}
      backdrop="static"
      keyboard={false}
      aria-labelledby="getAPIKey"
      animation={false}
      centered>
      <Modal.Header>
        <Modal.Title id="getAPIKey">Authentication</Modal.Title>
      </Modal.Header>
      <Modal.Body>
        {error ? (
          <Alert key="danger" variant="danger">
            {constants.API_ERROR_MSG}
          </Alert>
        ) : null}
        <label htmlFor="keyInput" className="col-form-label fw-normal">
          <span>Trimble Maps SDK API Key</span>
          <span className="required">*</span>
        </label>
        <input
          ref={inputRef}
          defaultValue={apiKey}
          className="form-control"
          id="keyInput"
          maxLength="32"
          minLength="32"
          placeholder="API Key"
          type="password"
          required
        />
        <div className="fst-italic mt-1">
          To gain access you must have an API key. Please contact your Trimble
          Maps representative or our{" "}
          <a
            href="https://maps.trimble.com/contact/"
            target="_blank"
            rel="noopener noreferrer">
            Sales team
          </a>{" "}
          for more information.
        </div>
      </Modal.Body>
      <Modal.Footer>
        <Button type="submit" className="btn btn-primary" onClick={submit}>
          Submit
        </Button>
      </Modal.Footer>
    </Modal>
  );
}

export default GetAPIKeyModal;
