// react-js-demo/src/components/MapStyle/MapStyle.jsx
import React, { useState, useEffect } from "react";
import {
  mapStyleOptions,
  mapStyleOptionsWithoutSatellitePremium,
} from "../../Utils/mapStyle";
import { useMapContext } from "../../context/mapContext";
import { useOutletContext } from "react-router-dom";

function MapStyle() {
  const { map, mapService } = useMapContext();
  const { licensedFeature } = useOutletContext();
  const [mapStyles, setMapStyles] = useState(mapStyleOptions);
  const defaultStyle = mapStyleOptions.findIndex(
    (opt) => opt.value === map.getStyleName()
  );
  const [selectedStyle, setSelectedStyle] = useState(defaultStyle);
  useEffect(() => {
    if (!licensedFeature.premiumSatellite) {
      setMapStyles(mapStyleOptionsWithoutSatellitePremium);
    }
  }, [licensedFeature]);
  const selectStyle = (event) => {
    const optionIndex = event.target.value;
    const setValue = mapStyleOptions[optionIndex];
    setSelectedStyle(optionIndex);
    mapService.changeStyle(map, setValue.value, setValue?.satelliteProvider);
  };

  return (
    <div className="modus-panel panel-lg h-100 shadow">
      <div className="panel-header">
        <h4>Styling</h4>
      </div>
      <div className="panel-body flex-fill">
        <div className="static-container d-flex align-items-center justify-content-start">
          <div className="form-group w-100">
            <ul>
              <li>Ability to change the display style of the map.</li>
            </ul>
            <label htmlFor="mapStyle">Map Style</label>
            <select
              name="selectedStyle"
              id="mapStyle"
              onChange={selectStyle}
              className="form-control"
              value={selectedStyle}
            >
              {mapStyles.map((item, index) => (
                <option
                  key={item.value + index}
                  value={index}
                  disabled={item.requireLicense}
                >
                  {item.requireLicense
                    ? item.displayName + " (Unlicensed Feature)"
                    : item.displayName}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>
    </div>
  );
}

export default MapStyle;

// angular-demo/src/app/components/map-style/map-style.component.ts
import { Component, OnDestroy, OnInit } from "@angular/core";
import { LicenseFeature } from "src/app/models/license";
import { StyleOption, mapStyleOptions } from "src/app/models/mapStyle";
import { MapService } from "src/app/services/map.service";
import { SubscriptionManager } from "src/app/utils/subscription-manager";

@Component({
  selector: "app-map-style",
  templateUrl: "./map-style.component.html",
  styleUrls: ["./map-style.component.scss"],
})
export class MapStyleComponent implements OnInit, OnDestroy {
  license!: LicenseFeature;
  constructor(private mapService: MapService) {}
  selectedStyle!: StyleOption;
  mapstyles: StyleOption[] = [];
  private sm = new SubscriptionManager();
  selectStyle() {
    this.mapService.changeStyle(
      this.selectedStyle.value,
      this.selectedStyle?.satelliteProvider
    );
  }
  ngOnInit() {
    this.sm.add(
      this.mapService.license$.subscribe((license) => {
        this.license = license;
        this.mapstyles = mapStyleOptions;
        this.selectedStyle = mapStyleOptions[0];
      })
    );
    this.sm.add(
      this.mapService.currentStyle$.subscribe((style) => {
        this.selectedStyle = this.mapstyles.filter(
          (value) => value.value === style
        )[0];
      })
    );
  }

  ngOnDestroy() {
    this.sm.unsubscribe();
  }
}

<div class="modus-panel panel-lg h-100 shadow">
    <div class="panel-header">
      <h4>Styling</h4>
    </div>
    <div class="panel-body flex-fill" >
      <div class="static-container d-flex align-items-center justify-content-start">
      <div class="form-group w-100">
          <ul>
            <li>
                Ability to change the display style of the map.
            </li>
          </ul>
          <label for="mapStyle">Map Style</label>
          <select
          name="selectedStyle"
          id="mapRegionSelector"
          (change)="selectStyle()"
          class="form-control"
          [(ngModel)]="selectedStyle"

        >
          <option
            *ngFor="let mapstyle of mapstyles"
            [ngValue]="mapstyle" [disabled] ="!license.premiumSatellite && mapstyle.requiresLicense"
          >
            {{ !license.premiumSatellite && mapstyle.requiresLicense? mapstyle.displayName +" (Unlicensed Feature)":mapstyle.displayName}}
          </option>
        </select>

        </div>
      </div>
      </div>
  </div>
