// angular-demo/src/app/components/content-layers/content-layers.component.ts
import { Component, OnDestroy, OnInit } from "@angular/core";
import * as TrimbleMaps from "@trimblemaps/trimblemaps-js";
import { Subject, combineLatest, takeUntil } from "rxjs";
import { layerSpecificLocation } from "src/app/utils/layerSpecificLocation";
import { MapService } from "src/app/services/map.service";
import { SubscriptionManager } from "src/app/utils/subscription-manager";
import { ModalService } from "../modal.service";
import { LicenseFeature } from "src/app/models/license";

@Component({
  selector: "app-content-layers",
  templateUrl: "./content-layers.component.html",
  styleUrls: ["./content-layers.component.scss"],
})
export class ContentLayersComponent implements OnInit, OnDestroy {
  region!: string;
  isNA!: boolean;
  isEU!: boolean;
  private sm = new SubscriptionManager();
  license!: LicenseFeature;
  activeAccordionIndex: number | null = null;
  constructor(
    private mapService: MapService,
    private modalService: ModalService
  ) {}
  pageloaded = new Subject();
  ngOnInit() {
    this.sm.add(
      combineLatest([
        this.mapService.currentRegion$,
        this.mapService.apiKey,
        this.mapService.isMapStyleLoaded$,
        this.mapService.license$,
      ])
        .pipe(takeUntil(this.pageloaded))
        .subscribe(([region, apiKey, isMapStyleLoaded, license]) => {
          if (apiKey && isMapStyleLoaded && Object.keys(license).length > 0) {
            this.region = region;
            this.isNA = region === TrimbleMaps.Common.Region.NA;
            this.isEU = region === TrimbleMaps.Common.Region.EU;
            this.license = license;
            this.openLayer(0);
            this.pageloaded.next(true);
            this.pageloaded.complete();
          }
        })
    );
    this.sm.add(
      combineLatest([
        this.mapService.apiKey,
        this.mapService.showLoading$,
      ]).subscribe(([apiKey, showLoading]) => {
        if (apiKey) {
          if (showLoading) {
            this.modalService.addLoading("Loading");
          } else {
            this.modalService.hideLoading();
          }
        }
      })
    );
  }
  openLayer(i: number) {
    this.mapService.resetMapLayers();
    if (this.activeAccordionIndex === i) {
      this.activeAccordionIndex = null;
    } else {
      this.activeAccordionIndex = i;
    }

    switch (i) {
      case 0:
        if (this.license?.traffic) {
          this.mapService.changeMapLocation(
            layerSpecificLocation(this.region, "traffic")
          );
          this.mapService.toggleTrafficVisibility();
        }
        break;

      case 1:
        this.mapService.toggleWeatherRadarVisibility();
        break;

      case 2:
        this.mapService.toggleWeatherAlertVisibility();
        break;

      case 3:
        this.mapService.toggleRoadSurfaceVisibility();
        break;

      case 4:
        this.mapService.changeMapLocation(
          layerSpecificLocation(this.region, "places")
        );
        this.mapService.togglePlacesVisibility();
        break;

      case 5:
        this.mapService.changeMapLocation(
          layerSpecificLocation(this.region, "poi")
        );
        this.mapService.togglePOIVisibility();
        break;

      case 6:
        this.mapService.changeMapLocation(
          layerSpecificLocation(this.region, "3dBuilding")
        );
        this.mapService.toggle3dBuildingVisibility(false);

        break;
      case 7:
        this.mapService.changeMapLocation(
          layerSpecificLocation(this.region, "trafficIncident")
        );
        this.mapService.addTrafficIncidentLayer();

        break;
      case 8:
        this.mapService.changeMapLocation(
          layerSpecificLocation(this.region, "truckRestriction")
        );
        this.mapService.addTruckRestrictionLayer();
        break;
      case 9:
        if (this.region === TrimbleMaps.Common.Region.NA) {
          this.mapService.addCustomPlaceLayerNA(
            layerSpecificLocation(this.region, "customPlacesLocation")
          );
        } else {
          this.mapService.addCustomPlaceLayerEU(
            layerSpecificLocation(this.region, "customPlacesLocation")
          );
        }

        break;

      default:
    }
  }

  addLoading() {
    this.modalService.addLoading("Loading...");
  }

  ngOnDestroy() {
    this.sm.unsubscribe();
  }
}

<div class="modus-panel panel-lg h-100 shadow">
  <div class="panel-header">
    <h4>Content Layers</h4>

  </div>
  <div class="accordion thead-light" id="contentLayer" *ngIf ="license">
    <div class="card">
      <div
        class="card-header"
        id="accordionHeadingOne"
        [attr.aria-expanded] ="activeAccordionIndex === 0?'true':'false'"
        aria-controls="codeCollapseOne"
        (click)="license.traffic?openLayer(0):null"
        (keyup)="license.traffic?openLayer(0):null"
        [ngClass]="{ 'unlicensed': !license.traffic }"
        role="button"
        tabindex="0">
        <h6  [ngClass]="{ 'disabled': !license.traffic }" class="mb-0 accordion-title" id="collapsible-group-item-1">Traffic</h6>
        <app-tooltip [showTooltip] ="!license.traffic"></app-tooltip>


      </div>
      <div
        id="codeCollapseOne"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show':license.traffic&&activeAccordionIndex === 0  }"
        aria-labelledby="accordionHeadingOne"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>Indicates the flow of traffic based on 4 congestion levels.</li>
            <li>Visible at zoom level 9 and greater.</li>
          </ul>
          <div
            class="panel-header bg-transparent mb-1"
           >
            <h5>Traffic Key</h5>
          </div>
          <svg
            class="bi pe-none me-2"
            width="18"
            height="18"
            style="background: green"></svg>
          No/Little Traffic<br />
          <svg
            class="bi pe-none me-2"
            width="18"
            height="18"
            style="background: orange"></svg>
          Light Traffic<br />
          <svg
            class="bi pe-none me-2"
            width="18"
            height="18"
            style="background: red"></svg>
          Heavy Traffic<br />
          <svg
            class="bi pe-none me-2"
            width="18"
            height="18"
            style="background: black"></svg>
          Road Closed
        </div>
      </div>
    </div>
    <div class="card" >
      <div
        class="card-header"
        id="accordionHeadingTwo"
        [attr.aria-expanded] ="activeAccordionIndex === 1?'true':'false'"
        aria-controls="codeCollapseTwo"
        role="button"
        (click)="license.weatherRadar&&openLayer(1)"
        (keyup)="license.weatherRadar&&openLayer(1)"
        [ngClass]="{ 'unlicensed': !license.weatherRadar }" tabindex="0">
         <h6  [ngClass]="{ 'disabled': !license.weatherRadar}" class="mb-0 accordion-title" id="collapsible-group-item-2">Weather Radar</h6>
         <app-tooltip [showTooltip] ="!license.weatherRadar"></app-tooltip>

      </div>
      <div
        id="codeCollapseTwo"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show': activeAccordionIndex === 1 }"
        aria-labelledby="accordionHeadingTwo"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>Displays weather radar overlay on map.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="card" *ngIf="isNA">
      <div
        class="card-header"
        id="accordionHeadingThree"
        data-toggle="collapse"
        aria-controls="codeCollapseThree"
        role="button"
        [ngClass]="{ 'unlicensed': !(isNA && license.weatherAlerts) }"
        (click)="isNA && license.weatherAlerts&&openLayer(2)"
        (keyup)="isNA && license.weatherAlerts&&openLayer(2)"
        tabindex="0">
         <h6   [ngClass]="{ 'disabled': !(isNA && license.weatherAlerts) }"class="mb-0 accordion-title" id="collapsible-group-item-3">Weather Alerts</h6>
         <app-tooltip [showTooltip] ="(isNA && !license.weatherAlerts)"
      ></app-tooltip>
      </div>
      <div
        id="codeCollapseThree"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show':activeAccordionIndex === 2 }"
        aria-labelledby="accordionHeadingThree"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>
              Displays weather alerts for various weather events only in North
              America.
            </li>
            <li>Can add click event to layer to display event information.</li>
            <li>
              Alert Filter Control can toggle visibility of different alert
              severity, urgency and certainty.
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="card" *ngIf="isNA">
      <div
        class="card-header"
        id="accordionHeadingFour"
        [attr.aria-expanded] ="activeAccordionIndex === 3?'true':'false'"
        aria-controls="codeCollapseFour"
        role="button"
        [ngClass]="{ 'unlicensed': !(isNA && license.roadSurface) }"
        (click)="isNA && license.roadSurface&&openLayer(3)"
        (keyup)="isNA && license.roadSurface&&openLayer(3)"
        tabindex="0">
         <h6 [ngClass]="{ 'disabled': !(isNA && license.roadSurface) }"class="mb-0 accordion-title" id="collapsible-group-item-4">Road Surface</h6>
         <app-tooltip [showTooltip] ="(isNA && !license.roadSurface)"
        ></app-tooltip>
      </div>
      <div
        id="codeCollapseFour"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show': activeAccordionIndex === 3 }"
        aria-labelledby="accordionHeadingFour"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>Displays road surface condition for North America.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="card" *ngIf="isNA">
      <div
        class="card-header"
        id="accordionHeadingFive"
        [attr.aria-expanded] ="activeAccordionIndex === 4?'true':'false'"
        aria-controls="codeCollapseFive"
        role="button"
        (click)="openLayer(4)"
        (keyup)="openLayer(4)"
        tabindex="0">
         <h6 class="mb-0 accordion-title" id="collapsible-group-item-5">Places</h6>
      </div>
      <div
        id="codeCollapseFive"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show': activeAccordionIndex === 4 }"
        aria-labelledby="accordionHeadingFive"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>
              Displays place polygon on the map, such as distribution centers
              and manufacturing facilities.
            </li>
            <li>
              Place information includes site polygon and truck entry/exit gates
              (where available).
            </li>
            <li>Includes points of interest icons.</li>
          </ul>
          <div
           class=" panel-header
            bg-transparent mb-1"
            >
            <h5>Gate Icons</h5>
          </div>
          <img
            src="assets/circle-outline-green.png"
            width="22"
            height="22"
            alt="" />Entrance Gate<br />
          <img
            src="assets/circle-outline-cyan.png"
            width="22"
            height="22"
            alt="" />Two-Way Gate<br />
          <img
            src="assets/circle-outline-red.png"
            width="22"
            height="22"
            alt="" />Exit Gate<br />
        </div>
      </div>
    </div>

    <div class="card" >
      <div
        class="card-header"
        id="accordionHeadingSix"
        [attr.aria-expanded] ="activeAccordionIndex === 5?'true':'false'"
        aria-controls="codeCollapseSix"
        role="button"
        (click)="license.poi&&openLayer(5)"
        (keyup)="license.poi&&openLayer(5)"
        [ngClass]="{ 'unlicensed': !(license.poi) }"
        tabindex="0">
         <h6 [ngClass]="{ 'disabled': !license.poi }" class="mb-0 accordion-title" id="collapsible-group-item-6">Points of Interest</h6>
         <app-tooltip [showTooltip] ="!license.poi"
        ></app-tooltip>
      </div>
      <div
        id="codeCollapseSix"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show': activeAccordionIndex === 5 }"
        aria-labelledby="accordionHeadingSix"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>Display points of interest icons on the map.</li>
          </ul>
          <div
            class="panel-header
            bg-transparent mb-1"
           >
            <h5>Example Place Icons</h5>
          </div>
          <img
            src="assets/poi_distribution_center.png"
            width="22"
            height="22"
            alt="" />Distribution Center<br />
          <img
            src="assets/poi_fuel.png"
            width="22"
            height="22"
            alt="" />Fuel<br />
          <img
            src="assets/poi_manufacturing_plant.png"
            width="22"
            height="22"
            alt="" />Manufacturing Plant<br />
          <img
            src="assets/poi_rest_area.png"
            width="22"
            height="22"
            alt="" />Rest Area<br />
        </div>
      </div>
    </div>
    <div class="card">
      <div
        class="card-header"
        id="accordionHeadingSeven"
        [attr.aria-expanded] ="activeAccordionIndex === 6?'true':'false'"
        aria-controls="codeCollapseSeven"
        role="button"
        (click)="openLayer(6)"
        (keyup)="openLayer(6)"
        tabindex="0">
         <h6 class="mb-0 accordion-title" id="collapsible-group-item-7">3D Buildings</h6>
      </div>
      <div
        id="codeCollapseSeven"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show':activeAccordionIndex ===6 }"
        aria-labelledby="accordionHeadingSeven"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>Displays 3D buildings.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="card" >
      <div
        class="card-header"
        id="accordionHeadingEight"
        [attr.aria-expanded] ="activeAccordionIndex === 7?'true':'false'"
        aria-controls="codeCollapseEight"
        role="button"
        (click)="license.traffic&&openLayer(7)"
        (keyup)="license.traffic&&openLayer(7)"
        [ngClass]="{ 'unlicensed': !(license.traffic) }"
        tabindex="0">
         <h6 [ngClass]="{ 'disabled': !license.traffic }" class="mb-0 accordion-title" id="collapsible-group-item-8">Traffic Incidents</h6>
         <app-tooltip [showTooltip]  ="!license.traffic"
        ></app-tooltip>

      </div>
      <div
        id="codeCollapseEight"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show': activeAccordionIndex === 7 }"
        aria-labelledby="accordionHeadingEight"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>Displays current traffic incidents.</li>
            <li>
              Click event can be added to layer to show incident information.
            </li>
            <li>Control can be added to layer to filter incident types.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="card" >
      <div
        class="card-header"
        id="accordionHeadingNine"
        [attr.aria-expanded] ="activeAccordionIndex === 8?'true':'false'"
        aria-controls="codeCollapseNine"
        role="button"
        (click)="license.truckRestriction&&openLayer(8)"
        (keyup)="license.truckRestriction&&openLayer(8)"
        [ngClass]="{ 'unlicensed': !(license.truckRestriction) }"
        tabindex="0">
         <h6  [ngClass]="{ 'disabled': !license.truckRestriction }" class="mb-0 accordion-title" id="collapsible-group-item-9">Truck Restrictions</h6>
         <app-tooltip [showTooltip] ="!license.truckRestriction"
        ></app-tooltip>
      </div>
      <div
        id="codeCollapseNine"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show': activeAccordionIndex === 8 }"
        aria-labelledby="accordionHeadingNine"
        data-parent="#contentLayer">
        <div class="card-body">
          <ul>
            <li>Displays truck restrictions on the map.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="card">
      <div
        class="card-header"
        id="accordionHeadingTen"
        [attr.aria-expanded] ="activeAccordionIndex === 9?'true':'false'"
        aria-controls="codeCollapseTen"
        role="button"
        (click)="license.customData&&openLayer(9)"
        (keyup)="license.customData&&openLayer(9)"
        [ngClass]="{ 'unlicensed': !(license.customData) }"
        tabindex="0">
         <h6 [ngClass]="{ 'disabled': !license.customData }" class="mb-0 accordion-title" id="collapsible-group-item-10">Custom Content</h6>
         <app-tooltip [showTooltip] ="!license.customData"
        ></app-tooltip>
      </div>
      <div
        id="codeCollapseTen"
        class="collapse bg-gray-light"
        [ngClass]="{ 'show': activeAccordionIndex === 9 }"
        aria-labelledby="accordionHeadingTen"
        data-parent="#contentLayer">
        <div class="card-body">
          <div *ngIf="isNA">
            <ul>
              <li>
                Ability to plot custom data onto the map via geoJson objects.
              </li>
              <li>
                Information for this example is comprised of a geojson source
                that is broken down into 3 different custom content layers:
              </li>
              <ul>
                <li>
                  <b>Fill Layer</b>: Creates the state boundary polygon of New
                  Jersey and sets the opacity.
                </li>
                <li>
                  <b>Line Layer</b>: Forms the outline around the New Jersey
                  polygon.
                </li>
                <li>
                  <b>Symbol Layer</b>: Adds the Trimble Maps logo to the map.
                </li>
              </ul>
            </ul>
          </div>
          <div *ngIf="isEU">
            <ul>
              <li>
                Ability to plot custom data onto the map via geoJson objects.
              </li>
              <li>
                Information for this example is comprised of a geojson source
                that is broken down into 3 different custom content layers:
              </li>
              <ul>
                <li>
                  <b>Fill Layer</b>: Creates the country boundary polygon of
                  Great Britain and sets the opacity.
                </li>
                <li>
                  <b>Line Layer</b>: Forms the outline around the Great Britain
                  polygon.
                </li>
                <li>
                  <b>Symbol Layer</b>: Adds the Trimble Maps logo to the map.
                </li>
              </ul>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// react-js-demo/src/components/ContentLayers/ContentLayers.jsx
import React, { useState, useEffect } from "react";
import { useOutletContext } from "react-router-dom";
import { useMapContext } from "../../context/mapContext";
import TrimbleMaps from "@trimblemaps/trimblemaps-js";
import { layerSpecificLocation } from "../../Utils/layerSpecificlocation";
import Card from "react-bootstrap/Card";
import Accordion from "react-bootstrap/Accordion";
import CustomTooltip from "../ToolTip/CustomToolTip";

function ContentLayers() {
  const { map, mapService } = useMapContext();
  const { licensedFeature, setShowToast, setMessage } = useOutletContext();
  const [selected, setSelected] = useState(0);
  const region = map.getRegion();

  useEffect(() => {
    openLayer(selected);
  }, [selected]);
  const openLayer = (i) => {
    setShowToast(false);
    mapService.resetMapLayers(map);

    switch (i) {
      case 0: {
        if (!map.isTrafficVisible() && licensedFeature.traffic) {
          const mapLocation = layerSpecificLocation(region, "traffic");
          mapService.changeMapLocation(map, mapLocation);
          map.toggleTrafficVisibility();
        }
        break;
      }

      case 1: {
        map.toggleWeatherRadarVisibility();
        break;
      }
      case 2: {
        map.toggleWeatherAlertVisibility();
        map.on("weatheralert", () => {
          map.setWeatherAlertVisibility(true);
        });
        break;
      }

      case 3: {
        mapService.toggleRoadSurfaceVisibility(map);
        mapService.toggleRoadSurfaceVisibility(map);
        break;
      }

      case 4: {
        const place = layerSpecificLocation(region, "places");
        mapService.changeMapLocation(map, place);
        map.togglePlacesVisibility();
        map.setLayoutProperty("places_gates", "icon-size", 0.7);
        break;
      }

      case 5: {
        const poiLocation = layerSpecificLocation(region, "poi");
        mapService.changeMapLocation(map, poiLocation);
        map.togglePOIVisibility();
        break;
      }

      case 6: {
        if (
          map.getStyle().name.toLowerCase() ===
          TrimbleMaps.Common.Style.SATELLITE
        ) {
          setShowToast(true);
          setMessage({
            type: "warning",
            text: "3D buildings are unavailable in Satellite view"
          });
        } else {
          const d3BuildingLocation = layerSpecificLocation(
            region,
            "3dBuilding"
          );
          mapService.changeMapLocation(map, d3BuildingLocation);
          map.toggle3dBuildingVisibility();
          map.setPitch(60);
        }
        break;
      }

      case 7: {
        const trafficIncidentLocation = layerSpecificLocation(
          region,
          "trafficIncident"
        );
        mapService.changeMapLocation(map, trafficIncidentLocation);
        mapService.addTrafficIncidentLayer(map);
        break;
      }

      case 8: {
        const truckRestrictionLocation = layerSpecificLocation(
          region,
          "truckRestriction"
        );
        mapService.changeMapLocation(map, truckRestrictionLocation);
        mapService.addTruckRestrictionLayer(map);
        break;
      }
      case 9: {
        const customPlacesLocation = layerSpecificLocation(
          region,
          "customPlacesLocation"
        );
        if (region === TrimbleMaps.Common.Region.NA) {
          mapService.addCustomPlaceLayerNA(map, customPlacesLocation);
        } else {
          mapService.addCustomPlaceLayerEU(map, customPlacesLocation);
        }

        break;
      }

      default:
    }
  };
  return (
    <>
      <div className="modus-panel panel-lg h-100 shadow">
        <div className="panel-header">
          <h4>Content Layers</h4>
        </div>
        <Accordion defaultActiveKey="0">
          <Card
            onClick={() => {
              licensedFeature.traffic ? setSelected(0) : null;
            }}>
            <Accordion.Toggle
              as={Card.Header}
              eventKey="0"
              className={!licensedFeature.traffic ? "unlicensed" : ""}
            >
              <h6
                className={
                  !licensedFeature.traffic
                    ? "disabled mb-0 d-inline"
                    : "mb-0 d-inline"
                }
                id="collapsible-group-item-1"
              >
                Traffic
              </h6>
              <CustomTooltip
                showToolTip={!licensedFeature.traffic}></CustomTooltip>
            </Accordion.Toggle>
            {licensedFeature.traffic ? (
              <Accordion.Collapse eventKey="0">
                <Card.Body>
                  <ul>
                    <li>
                      Indicates the flow of traffic based on 4 congestion
                      levels.
                    </li>
                    <li>Visible at zoom level 9 and greater.</li>
                  </ul>
                  <div className="panel-header bg-transparent mb-1">
                    <h5 className="px-2 text-center">Traffic Key</h5>
                  <div className="panel-header bg-transparent mb-1">
                    <h5 className="px-2 text-center">Traffic Key</h5>
                  </div>
                  <svg
                    className="bi pe-none me-2 mr-2"
                    width="18"
                    height="18"
                    style={{ background: "green" }}></svg>
                  No/Little Traffic
                  <br />
                  <svg
                    className="bi pe-none me-2 mr-2"
                    width="18"
                    height="18"
                    style={{ background: "orange" }}></svg>
                  Light Traffic
                  <br />
                  <svg
                    className="bi pe-none me-2 mr-2"
                    width="18"
                    height="18"
                    style={{ background: "red" }}></svg>
                  Heavy Traffic
                  <br />
                  <svg
                    className="bi pe-none me-2 mr-2"
                    width="18"
                    height="18"
                    style={{ background: "black" }}></svg>
                  Road Closed
                </Card.Body>
              </Accordion.Collapse>
            ) : null}
          </Card>
          <Card
            onClick={() => {
              licensedFeature.weatherRadar ? setSelected(1) : null;
            }}>
            <Accordion.Toggle
              as={Card.Header}
              eventKey="1"
              className={!licensedFeature.weatherRadar ? "unlicensed" : ""}
            >
              <h6
                className={
                  !licensedFeature.weatherRadar
                    ? "disabled mb-0 d-inline"
                    : "mb-0 d-inline"
                }
                id="collapsible-group-item-1"
              >
                Weather Radar
              </h6>
              <CustomTooltip
                showToolTip={!licensedFeature.weatherRadar}></CustomTooltip>
            </Accordion.Toggle>
            {licensedFeature.weatherRadar ? (
              <Accordion.Collapse eventKey="1">
                <Card.Body>
                  <ul>
                    <li>Displays weather radar overlay on map.</li>
                  </ul>
                </Card.Body>
              </Accordion.Collapse>
            ) : null}
          </Card>

          {region === TrimbleMaps.Common.Region.NA ? (
            <Card
              onClick={() => {
                licensedFeature.weatherAlerts ? setSelected(2) : null;
              }}>
              <Accordion.Toggle
                as={Card.Header}
                eventKey="2"
                className={!licensedFeature.weatherAlerts ? "unlicensed" : ""}
              >
                <h6
                  className={
                    !licensedFeature.weatherAlerts
                      ? "disabled mb-0 d-inline"
                      : "mb-0 d-inline"
                  }
                  id="collapsible-group-item-1"
                >
                  Weather Alerts
                </h6>
                <CustomTooltip
                  showToolTip={!licensedFeature.weatherAlerts}></CustomTooltip>
              </Accordion.Toggle>
              {licensedFeature.weatherAlerts ? (
                <Accordion.Collapse eventKey="2">
                  <Card.Body>
                    <ul>
                      <li>
                        Displays weather alerts for various weather events only
                        in North America.
                      </li>
                      <li>
                        Can add click event to layer to display event
                        information.
                      </li>
                      <li>
                        Alert Filter Control can toggle visibility of different
                        alert severity, urgency and certainty.
                      </li>
                    </ul>
                  </Card.Body>
                </Accordion.Collapse>
              ) : null}
            </Card>
          ) : null}
          {region === TrimbleMaps.Common.Region.NA ? (
            <Card
              onClick={() => {
                licensedFeature.roadSurface ? setSelected(3) : null;
              }}>
              <Accordion.Toggle
                as={Card.Header}
                eventKey="3"
                className={!licensedFeature.roadSurface ? "unlicensed" : ""}
              >
                <h6
                  className={
                    !licensedFeature.roadSurface
                      ? "disabled mb-0 d-inline"
                      : "mb-0 d-inline"
                  }
                  id="collapsible-group-item-1"
                >
                  Road Surface
                </h6>
                <CustomTooltip
                  showToolTip={!licensedFeature.roadSurface}></CustomTooltip>
              </Accordion.Toggle>
              {licensedFeature.roadSurface ? (
                <Accordion.Collapse eventKey="3">
                  <Card.Body>
                    <ul>
                      <li>
                        Displays road surface condition for North America.
                      </li>
                    </ul>
                  </Card.Body>
                </Accordion.Collapse>
              ) : null}
            </Card>
          ) : null}
          {region === TrimbleMaps.Common.Region.NA ? (
            <Card
              onClick={() => {
                setSelected(4);
              }}>
              <Accordion.Toggle as={Card.Header} eventKey="4">
                <h6 className="mb-0" id="collapsible-group-item-1">
                  Places
                </h6>
              </Accordion.Toggle>
              <Accordion.Collapse eventKey="4">
                <Card.Body>
                  <ul>
                    <li>
                      Displays place polygon on the map, such as distribution
                      centers and manufacturing facilities.
                    </li>
                    <li>
                      Place information includes site polygon and truck
                      entry/exit gates (where available).
                    </li>
                    <li>Includes points of interest icons.</li>
                  </ul>
                  <div className="panel-header bg-transparent mb-1">
                    <h5 className="px-2 text-center">Gate Icons</h5>
                  <div className="panel-header bg-transparent mb-1">
                    <h5 className="px-2 text-center">Gate Icons</h5>
                  </div>
                  <img
                    src={"../../assets/img/circle-outline-green.png"}
                    width="22"
                    height="22"
                    alt=""
                  />
                  Entrance Gate
                  <br />
                  <img
                    src={"../../assets/img/circle-outline-cyan.png"}
                    width="22"
                    height="22"
                    alt=""
                  />
                  Two-Way Gate
                  <br />
                  <img
                    src="../../assets/img/circle-outline-red.png"
                    width="22"
                    height="22"
                    alt=""
                  />
                  Exit Gate
                  <br />
                </Card.Body>
              </Accordion.Collapse>
            </Card>
          ) : null}

          <Card
            onClick={() => {
              licensedFeature.poi ? setSelected(5) : null;
            }}>
            <Accordion.Toggle
              as={Card.Header}
              eventKey="5"
              className={!licensedFeature.poi ? "unlicensed" : ""}
            >
              <h6
                className={
                  !licensedFeature.poi
                    ? "disabled mb-0 d-inline"
                    : "mb-0 d-inline"
                }
                id="collapsible-group-item-1"
              >
                Point of Interest
              </h6>
              <CustomTooltip showToolTip={!licensedFeature.poi}></CustomTooltip>
            </Accordion.Toggle>
            {licensedFeature.poi ? (
              <Accordion.Collapse eventKey="5">
                <Card.Body>
                  <ul>
                    <li>Display points of interest icons on the map.</li>
                  </ul>
                  <div className="panel-header bg-transparent mb-1">
                    <h5 className="px-2 text-center">Example Place Icons</h5>
                  <div className="panel-header bg-transparent mb-1">
                    <h5 className="px-2 text-center">Example Place Icons</h5>
                  </div>
                  <img
                    src="../../assets/img/poi_distribution_center.png"
                    width="22"
                    height="22"
                    alt=""
                  />
                  Distribution Center
                  <br />
                  <img
                    src="../../assets/img/poi_fuel.png"
                    width="22"
                    height="22"
                    alt=""
                  />
                  Fuel
                  <br />
                  <img
                    src="../../assets/img/poi_manufacturing_plant.png"
                    width="22"
                    height="22"
                    alt=""
                  />
                  Manufacturing Plant
                  <br />
                  <img
                    src="../../assets/img/poi_rest_area.png"
                    width="22"
                    height="22"
                    alt=""
                  />
                  Rest Area
                  <br />
                </Card.Body>
              </Accordion.Collapse>
            ) : null}
          </Card>

          <Card
            onClick={() => {
              setSelected(6);
            }}>
            <Accordion.Toggle as={Card.Header} eventKey="6">
              <h6 className="mb-0" id="collapsible-group-item-1">
                3D Building
              </h6>
            </Accordion.Toggle>
            <Accordion.Collapse eventKey="6">
              <Card.Body>
                <ul>
                  <li>Displays 3D buildings.</li>
                </ul>
              </Card.Body>
            </Accordion.Collapse>
          </Card>

          <Card
            onClick={() => {
              licensedFeature.traffic ? setSelected(7) : null;
            }}>
            <Accordion.Toggle
              as={Card.Header}
              eventKey="7"
              className={!licensedFeature.traffic ? "unlicensed" : ""}
            >
              <h6
                className={
                  !licensedFeature.traffic
                    ? "disabled mb-0 d-inline"
                    : "mb-0 d-inline"
                }
                id="collapsible-group-item-1"
              >
                Traffic Incidents
              </h6>
              <CustomTooltip
                showToolTip={!licensedFeature.traffic}></CustomTooltip>
            </Accordion.Toggle>
            {licensedFeature.traffic ? (
              <Accordion.Collapse eventKey="7">
                <Card.Body>
                  <div className="card-body">
                    <ul>
                      <li>Displays current traffic incidents.</li>
                      <li>
                        Click event can be added to layer to show incident
                        information.
                      </li>
                      <li>
                        Control can be added to layer to filter incident types.
                      </li>
                    </ul>
                  </div>
                </Card.Body>
              </Accordion.Collapse>
            ) : null}
          </Card>

          <Card
            onClick={() => {
              licensedFeature.truckRestriction ? setSelected(8) : null;
            }}>
            <Accordion.Toggle
              as={Card.Header}
              eventKey="8"
              className={!licensedFeature.truckRestriction ? "unlicensed" : ""}
            >
              <h6
                className={
                  !licensedFeature.truckRestriction
                    ? "disabled mb-0 d-inline"
                    : "mb-0 d-inline"
                }
                id="collapsible-group-item-1"
              >
                Truck Restrictions
              </h6>
              <CustomTooltip
                showToolTip={!licensedFeature.truckRestriction}></CustomTooltip>
            </Accordion.Toggle>
            {licensedFeature.truckRestriction ? (
              <Accordion.Collapse eventKey="8">
                <Card.Body>
                  <ul>
                    <li>Displays truck restrictions on the map.</li>
                  </ul>
                </Card.Body>
              </Accordion.Collapse>
            ) : null}
          </Card>

          <Card
            onClick={() => {
              licensedFeature.customData ? setSelected(9) : null;
            }}>
            <Accordion.Toggle
              as={Card.Header}
              eventKey="9"
              className={!licensedFeature.customData ? "unlicensed" : ""}
            >
              <h6
                className={
                  !licensedFeature.customData
                    ? "disabled mb-0 d-inline"
                    : "mb-0 d-inline"
                }
                id="collapsible-group-item-1"
              >
                Custom Content
              </h6>
              <CustomTooltip
                showToolTip={!licensedFeature.customData}></CustomTooltip>
            </Accordion.Toggle>
            {licensedFeature.customData ? (
              <Accordion.Collapse eventKey="9">
                <Card.Body>
                  {region === TrimbleMaps.Common.Region.NA ? (
                    <div>
                      <ul>
                        <li>
                          Ability to plot custom data onto the map via geoJson
                          objects.
                        </li>
                        <li>
                          Information for this example is comprised of a geojson
                          source that is broken down into 3 different custom
                          content layers:
                        </li>
                        <ul>
                          <li>
                            <b>Fill Layer</b>: Creates the state boundary
                            polygon of New Jersey and sets the opacity.
                          </li>
                          <li>
                            <b>Line Layer</b>: Forms the outline around the New
                            Jersey polygon.
                          </li>
                          <li>
                            <b>Symbol Layer</b>: Adds the Trimble MAPS logo to
                            the map.
                          </li>
                        </ul>
                      </ul>
                    </div>
                  ) : (
                    <div>
                      <ul>
                        <li>
                          Ability to plot custom data onto the map via geoJson
                          objects.
                        </li>
                        <li>
                          Information for this example is comprised of a geojson
                          source that is broken down into 3 different custom
                          content layers:
                        </li>
                        <ul>
                          <li>
                            <b>Fill Layer</b>: Creates the country boundary
                            polygon of Great Britain and sets the opacity.
                          </li>
                          <li>
                            <b>Line Layer</b>: Forms the outline around the
                            Great Britain polygon.
                          </li>
                          <li>
                            <b>Symbol Layer</b>: Adds the Trimble Maps logo to
                            the map.
                          </li>
                        </ul>
                      </ul>
                    </div>
                  )}
                </Card.Body>
              </Accordion.Collapse>
            ) : null}
          </Card>
        </Accordion>
      </div>
    </>
  );
}

export default ContentLayers;
