// react-js-demo/src/components/SiteLocationRouting/SiteLocationRouting.jsx
import React, { useState, useEffect } from "react";
import { useMapContext } from "../../context/mapContext";
import TrimbleMaps from "@trimblemaps/trimblemaps-js";
import useSiteRouting from "../../hooks/useSiteRouting";
import { siteLocation } from "../../Utils/siteLocation";
import * as _ from "lodash";
import LoadingModal from "../sharedComponents/LoadingModal";

function SiteLocationRouting() {
  const { map, mapService } = useMapContext();
  const [siteEnabled, setSiteEnabled] = useState(false);
  const [show, setShow] = useState(true);
  const PLACE_ID = "0xZqVCm3sA0k--1OtaidIcpQ";

  const siteGateFeatures = useSiteRouting(PLACE_ID, TrimbleMaps.APIKey);

  useEffect(() => {}, []);

  useEffect(() => {
    if (!_.isEmpty(siteGateFeatures)) {
      const siteGateGeojson = {
        type: "geojson",
        data: {
          type: "FeatureCollection",
          features: siteGateFeatures,
        },
      };
      mapService.addSiteLocation(map, siteGateGeojson);
      createSiteRoute();
      setShow(false);
    }
  }, [siteGateFeatures]);

  const toggleSiteLocationRouting = () => {
    setSiteEnabled((prev) => !prev);
    mapService.updateSite(!siteEnabled);
  };

  const createSiteRoute = () => {
    const routeCoords = siteLocation(TrimbleMaps.Common.Region.NA);
    mapService.createRoute(
      map,
      routeCoords,
      TrimbleMaps.Common.RouteType.PRACTICAL,
      TrimbleMaps.Common.VehicleType.TRUCK,
      false,
      TrimbleMaps.Common.TollRoadsType.USE,
      true,
      TrimbleMaps.Common.HazMatType.NONE,
      siteEnabled,
      map.getRegion(),
      0
    );
  };

  return (
    <>
      <div className="modus-panel panel-lg h-100 shadow">
        <div className="panel-header">
          <h4>Site Routing</h4>
        </div>
        <div className="panel-body flex-fill">
          <div className="static-container d-flex align-items-center justify-content-start">
            <div className="form-group">
              <ul>
                <li>
                  Verified Trimble MAPS Places are publicly available locations
                  that contain site information such as place name, address,
                  operating hours, amenities and entry/exit gates.
                </li>
                <li>
                  Over 5 million locations with unique site geofence data (as of
                  October 2023).
                </li>
                <li>
                  Site gates used in routing can increase routing accuracy for
                  final mile stretches and alleviate driver frustration when
                  arriving at new locations.
                </li>
                <li>
                  Demonstration uses geojson layer to place Trimble MAPS gate
                  icons onto the map.
                </li>
              </ul>

              <div className="">
                <button
                  type="button"
                  className="btn btn-primary col-md-12"
                  id="optimizeBtn"
                  onClick={toggleSiteLocationRouting}
                >
                  <span>
                    {siteEnabled
                      ? "Disable Site Routing"
                      : "Enable Site Routing"}
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <LoadingModal
        setShow={setShow}
        show={show}
        loadingText={"Loading..."}
      ></LoadingModal>
    </>
  );
}

export default SiteLocationRouting;

// angular-demo/src/app/components/site-location-routing/site-location-routing.component.ts
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";
import * as TrimbleMaps from "@trimblemaps/trimblemaps-js";
import { combineLatest } from "rxjs";
import { MapRegion } from "src/app/models/trimbleMaps";
import { MapService } from "src/app/services/map.service";
import { SiteRoutingPlacesService } from "src/app/services/site-routing-places.service";
import { siteLocation } from "src/app/utils/site-location";
import { SubscriptionManager } from "src/app/utils/subscription-manager";

@Component({
  selector: "app-site-location-routing",
  templateUrl: "./site-location-routing.component.html",
})
export class SiteLocationRoutingComponent implements OnInit {
  isNA!: boolean;
  isEU!: boolean;
  region!: MapRegion;
  siteEnabled = false;
  private sm = new SubscriptionManager();
  constructor(
    private mapService: MapService,
    private siteRoutingPlacesService: SiteRoutingPlacesService,
    private router: Router
  ) {}

  ngOnInit() {
    this.sm.add(
      combineLatest([
        this.mapService.currentRegion$,
        this.mapService.apiKey,
        this.mapService.isMapStyleLoaded$,
      ]).subscribe(([region, apiKey, isMapStyleLoaded]) => {
        if (this.router.url === "/siteLocationRouting") {
          if (apiKey && isMapStyleLoaded) {
            this.region = region;
            this.isNA = region === TrimbleMaps.Common.Region.NA;
            this.isEU = region === TrimbleMaps.Common.Region.EU;
            this.createSiteRoute();
          }
        }
      })
    );
  }

  createSiteRoute() {
    let placeID;
    if (this.region === TrimbleMaps.Common.Region.NA) {
      placeID = "0xZqVCm3sA0k--1OtaidIcpQ";
    } else {
      placeID = "AmazonWarehouseDemo";
      this.mapService.addSiteEULayer();
    }

    const routeCoords = siteLocation(this.region);
    this.mapService.createRoute(
      routeCoords,
      TrimbleMaps.Common.RouteType.PRACTICAL,
      TrimbleMaps.Common.VehicleType.TRUCK,
      false,
      TrimbleMaps.Common.TollRoadsType.USE,
      true,
      TrimbleMaps.Common.HazMatType.NONE,
      this.siteEnabled,
      this.region,
      0
    );

    this.siteRoutingPlacesService
      .createSiteRoutingPlaces(placeID)
      .subscribe((siteGateFeatures: any) => {
        const siteGateGeojson = {
          type: "geojson",
          data: {
            type: "FeatureCollection",
            features: siteGateFeatures,
          },
        };

        this.mapService.addSiteLocation(siteGateGeojson);
      });
  }

  toggleSiteLocationRouting() {
    this.siteEnabled = !this.siteEnabled;
    this.mapService.updateSite(this.siteEnabled);
  }
}

<div class="modus-panel panel-lg h-100 shadow">
  <div class="panel-header">
    <h4>Site Routing</h4>
  </div>
  <div class="panel-body flex-fill">
    <div
      class="static-container d-flex align-items-center justify-content-start">
      <div class="form-group">
        <ul *ngIf="isNA">
          <li>
            Verified Trimble Maps Places are publicly available locations that
            contain site information such as place name, address, operating
            hours, amenities and entry/exit gates.
          </li>
          <li>
            Over 5 million locations with unique site geofence data (as of
            October 2023).
          </li>
          <li>
            Site gates used in routing can increase routing accuracy for final
            mile stretches and alleviate driver frustration when arriving at new
            locations.
          </li>
          <li>
            Demonstration uses geojson layer to place Trimble Maps gate icons
            onto the map.
          </li>
        </ul>
        <ul *ngIf="isEU">
          <li>
            Through the use of Content Tools, customized sites and entrance/exit
            gates can be created for more personalized routing.
          </li>
          <li>
            Site gates used in routing can increase routing accuracy for final
            mile stretches and alleviate driver frustration when arriving at new
            locations.
          </li>
          <li>
            Demonstration uses geojson layers to place Trimble Maps gate icons
            onto the map and fill site perimeter.
          </li>
        </ul>

        <div class="">
          <button
            type="button"
            class="btn btn-primary col-md-12"
            id="optimizeBtn"
            (click)="toggleSiteLocationRouting()">
            <span *ngIf="!siteEnabled">Enable Site Routing</span>
            <span *ngIf="siteEnabled">Disable Site Routing</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
