// angular-demo/src/app/components/time-window-routing/time-window-routing.component.ts
import { Component, OnInit } from "@angular/core";
import * as TrimbleMaps from "@trimblemaps/trimblemaps-js";
import { Observable, combineLatest, forkJoin, take } from "rxjs";
import { MapRegion } from "src/app/models/trimbleMaps";
import { MapService } from "src/app/services/map.service";
import { TimeWindowRoutingService } from "src/app/services/time-window.service";

import { ModalService } from "../modal.service";
import { Router } from "@angular/router";

@Component({
  selector: "app-time-window-routing",
  templateUrl: "./time-window-routing.component.html",
  styleUrls: ["./time-window-routing.component.scss"],
})
export class TimeWindowRoutingComponent implements OnInit {
  region!: MapRegion;
  titleText!: string;
  displayText!: string;
  routeOptimization = 2;
  routeDetails!: any;
  twBtnText = "Optimize";
  routeDetails$!: Observable<any>;
  optimizeRouteDetails$!: any;
  unOptimizeRouteDetails$!: any;
  optimizeRouteStops!: any;
  UnOptimizeRouteStops!: any;
  loadingModal: any;
  constructor(
    private mapService: MapService,
    private timeWindowService: TimeWindowRoutingService,
    private modalService: ModalService,
    private router: Router
  ) {}
  ngOnInit() {
    combineLatest([
      this.mapService.currentRegion$,
      this.mapService.apiKey,
      this.mapService.isMapStyleLoaded$,
    ]).subscribe(([region, apiKey, styleLoaded]) => {
      if (this.router.url === "/timeWindowRouting") {
        if (apiKey && styleLoaded) {
          this.region = region;
          this.titleText = "Route Optimization";
          this.displayText =
            '<li> Ability to feed in locations with time windows for optimization, will provide the best route path that accomidates as many time windows as possible, while returning locations that do not fit based on their time window information.</li><li>Utilizes the Time Window Routing API (<a href="https://developer.trimblemaps.com/restful-apis/routing/time-window-routing/" target="_blank">Documentation</a>).</li><li>Sample locations optimized assuming 40 minute dwell times at each location.</li>';

          this.addLoading();
          forkJoin(
            this.timeWindowService.getTimeWindowOptimization(this.region, 1),
            this.timeWindowService.getTimeWindowOptimization(this.region, 2)
          )
            .pipe(take(1))
            .subscribe((res: any) => {
              this.optimizeRouteDetails$ = res[0].routeDetails;
              this.optimizeRouteStops = res[0].routeStops;
              this.unOptimizeRouteDetails$ = res[1].routeDetails;
              this.UnOptimizeRouteStops = res[1].routeStops;
              this.mapService.createRoute(
                this.UnOptimizeRouteStops,
                TrimbleMaps.Common.RouteType.PRACTICAL,
                TrimbleMaps.Common.VehicleType.TRUCK,
                false,
                TrimbleMaps.Common.TollRoadsType.USE,
                false,
                TrimbleMaps.Common.HazMatType.NONE,
                false,
                this.region,
                0
              );

              this.hideLoading();
            });
        }
      }
    });
  }
  toggleTimeWindowRouting() {
    this.mapService.removeRoutes();
    if (this.routeOptimization === 2) {
      this.twBtnText = "Revert";
      this.routeOptimization = 1;
      this.mapService.createRoute(
        this.optimizeRouteStops,
        TrimbleMaps.Common.RouteType.PRACTICAL,
        TrimbleMaps.Common.VehicleType.TRUCK,
        false,
        TrimbleMaps.Common.TollRoadsType.USE,
        false,
        TrimbleMaps.Common.HazMatType.NONE,
        false,
        this.region,
        0
      );
    } else {
      this.twBtnText = "Optimize";
      this.routeOptimization = 2;
      this.mapService.createRoute(
        this.UnOptimizeRouteStops,
        TrimbleMaps.Common.RouteType.PRACTICAL,
        TrimbleMaps.Common.VehicleType.TRUCK,
        false,
        TrimbleMaps.Common.TollRoadsType.USE,
        false,
        TrimbleMaps.Common.HazMatType.NONE,
        false,
        this.region,
        0
      );
    }
  }
  addLoading() {
    this.modalService.addLoading("Optimizing Route...");
  }
  hideLoading() {
    this.modalService.hideLoading();
  }
  ngonDestroy() {
    this.mapService.removeRoutes();
  }
}

<div class="modus-panel panel-lg h-100 shadow">
  <div class="panel-header">
    <h4>{{ titleText }}</h4>
  </div>
  <div class="panel-body flex-fill">
    <div
      class="static-container d-flex align-items-center justify-content-start">
      <div class="form-group">
        <ul [innerHtml]="displayText"></ul>
        <table class="table table-bordered table-sm" id="timeWindowTable">
          <thead>
            <tr>
              <th>Stop #</th>
              <th>Location</th>
              <th>Arrival</th>
              <th>Departure</th>
              <th>Time Window</th>
              <th>Window Met</th>
            </tr>
          </thead>
          <tbody>
            <ng-container *ngIf="routeOptimization === 2">
              <tr *ngFor="let routeDetail of unOptimizeRouteDetails$">
                <td>{{ routeDetail.stopNo }}</td>
                <td>{{ routeDetail.location }}</td>
                <td>{{ routeDetail.arrival }}</td>
                <td>{{ routeDetail.departure }}</td>
                <td>{{ routeDetail.timeWindow }}</td>

                <td>
                  <span *ngIf="routeDetail.windowMet"
                    ><i
                      class="modus-icons"
                      aria-hidden="true"
                      style="color: green"
                      >check_circle</i
                    ></span
                  >
                  <span *ngIf="!routeDetail.windowMet"
                    ><i
                      class="modus-icons"
                      aria-hidden="true"
                      style="color: red"
                      >warning</i
                    ></span
                  >
                </td>
              </tr>
            </ng-container>
            <ng-container *ngIf="routeOptimization === 1">
              <tr *ngFor="let routeDetail of optimizeRouteDetails$">
                <td>{{ routeDetail.stopNo }}</td>
                <td>{{ routeDetail.location }}</td>
                <td>{{ routeDetail.arrival }}</td>
                <td>{{ routeDetail.departure }}</td>
                <td>{{ routeDetail.timeWindow }}</td>

                <td>
                  <span *ngIf="routeDetail.windowMet"
                    ><i
                      class="modus-icons"
                      aria-hidden="true"
                      style="color: green"
                      >check_circle</i
                    ></span
                  >
                  <span *ngIf="!routeDetail.windowMet"
                    ><i
                      class="modus-icons"
                      aria-hidden="true"
                      style="color: red"
                      >warning</i
                    ></span
                  >
                </td>
              </tr>
            </ng-container>
          </tbody>
        </table>
        <div>
          <button
            type="button"
            class="btn btn-primary col-md-12"
            id="optimizeBtn"
            (click)="toggleTimeWindowRouting()">
            {{ twBtnText }}
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

// react-js-demo/src/components/TimeWindowRouting/timeWindowRouting.jsx
/* eslint-disable no-unused-vars */
import React from "react";
import { useMapContext } from "../../context/mapContext";
import TrimbleMaps from "@trimblemaps/trimblemaps-js";
import { useState, useEffect } from "react";
import useTimeWindowService from "../../hooks/useTimeWindowService";
import Button from "react-bootstrap/Button";
import LoadingModal from "../sharedComponents/LoadingModal";

function TimeWindowRouting() {
  const { map, mapService } = useMapContext();
  const [routeOptimization, setRouteOptimization] = useState(2);
  const [routeDetails, setRouteDetails] = useState([]);
  const [twBtnText, setTwBtnText] = useState("optimize");
  const [mapRoute, setMapRoute] = useState(undefined);
  const [show, setShow] = useState(true);
  const [loadingText, setLoadingText] = useState("Optimizing Route...");

  const twRes = useTimeWindowService(
    routeOptimization,
    map.getRegion(),
    TrimbleMaps.APIKey
  );

  let routeStops;

  let displayText = null;
  let titleText, optimize_btn_txt;
  titleText = "Route Optimization";
  optimize_btn_txt = "Optimize";
  displayText =
    '<li> Ability to feed in locations with time windows for optimization, will provide the best route path that accomidates as many time windows as possible, while returning locations that do not fit based on their time window information.</li><li>Utilizes the Time Window Routing API (<a href="https://developer.trimblemaps.com/restful-apis/routing/time-window-routing/" target="_blank">Documentation</a>).</li><li>Sample locations optimized assuming 40 minute dwell times at each location.</li>';

  useEffect(() => {
    if (twRes) {
      setShow(false);
      setRouteDetails(twRes.routeDetails);
      routeStops = twRes.routeStops;
      const mapRouteObj = mapService.createRoute(
        map,
        routeStops,
        TrimbleMaps.Common.RouteType.PRACTICAL,
        TrimbleMaps.Common.VehicleType.TRUCK,
        false,
        TrimbleMaps.Common.TollRoadsType.USE,
        false,
        TrimbleMaps.Common.HazMatType.NONE,
        false,
        map.getRegion(),
        0
      );
      setMapRoute(mapRouteObj);
    }
  }, [twRes]);

  const toggleTimeWindowRouting = () => {
    setShow(true);
    mapService.removeRoutes();
    if (routeOptimization === 2) {
      setTwBtnText("Revert");
      setRouteOptimization(1);
    } else {
      setTwBtnText(optimize_btn_txt);
      setRouteOptimization(2);
    }
  };

  return (
    <>
      <div className="modus-panel panel-lg h-100 shadow">
        <div className="panel-header">
          <h4>{titleText}</h4>
        </div>
        <div className="panel-body flex-fill">
          <div className="static-container d-flex align-items-center justify-content-start">
            <div className="form-group">
              <ul dangerouslySetInnerHTML={{ __html: displayText }}></ul>
              <table
                className="table table-bordered table-sm"
                id="timeWindowTable"
              >
                <thead>
                  <tr>
                    <th>Stop #</th>
                    <th>Location</th>
                    <th>Arrival</th>
                    <th>Departure</th>
                    <th>Time Window</th>
                    <th>Window Met</th>
                  </tr>
                </thead>
                <tbody>
                  <>
                    {routeDetails.map((routeDetail, index) => (
                      <tr key={"unOptimize" + index}>
                        <td>{routeDetail.stopNo}</td>
                        <td>{routeDetail.location}</td>
                        <td>{routeDetail.arrival}</td>
                        <td>{routeDetail.departure}</td>
                        <td>{routeDetail.timeWindow}</td>

                        <td>
                          {routeDetail.windowMet ? (
                            <span>
                              <i
                                className="modus-icons"
                                aria-hidden="true"
                                style={{ color: "green" }}
                              >
                                check_circle
                              </i>
                            </span>
                          ) : (
                            <span>
                              <i
                                className="modus-icons"
                                aria-hidden="true"
                                style={{ color: "red" }}
                              >
                                warning
                              </i>
                            </span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </>
                </tbody>
              </table>
              <div className="">
                <Button
                  type="button"
                  className="btn btn-primary col-md-12 text-capitalize"
                  id="optimizeBtn"
                  onClick={toggleTimeWindowRouting}
                >
                  {twBtnText}
                </Button>
              </div>
              <LoadingModal
                setShow={setShow}
                show={show}
                loadingText={loadingText}
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default TimeWindowRouting;
