// angular-sample-app/src/app/components/map/map.component.ts
import {
  Component,
  ElementRef,
  Input,
  OnDestroy,
  OnInit,
  ViewChild,
} from "@angular/core";
import * as TrimbleMaps from "@trimblemaps/trimblemaps-js";
import { mapInfoSelectedRegion } from "src/app/models/region";
import { MapService } from "src/app/services/map.service";

@Component({
  standalone: false,
  selector: "app-map",
  templateUrl: "./map.component.html",
  styleUrls: ["./map.component.scss"],
})
export class MapComponent implements OnInit, OnDestroy {
  map!: TrimbleMaps.Map;
  @Input() mapStyle = "TRANSPORTATION";
  @ViewChild("map", { static: true }) mapElement: ElementRef | undefined;

  constructor(private mapService: MapService) {}

  ngOnInit(): void {
    const mapInfo = mapInfoSelectedRegion("na");
    this.mapService.apiKey$.subscribe((apiKey) => {
      if (apiKey) {
        this.map = this.mapService.initMap(
          {
            container: this.mapElement?.nativeElement,
            style: "transportation",
            center: mapInfo.center,
            zoom: mapInfo.zoom,
            hash: false,
            region: mapInfo.region,
          },
          apiKey
        );
      }
    });
  }
  ngOnDestroy() {
    this.mapService.removeAllEvent();
  }
}

<div class="h-100" id="map" #map></div>

// react-js-demo/src/components/Map/map.jsx
import React, { useRef, useEffect } from "react";

import { mapInfoSelectedRegion } from "../../Utils/mapInfo";
import TrimbleMaps from "@trimblemaps/trimblemaps-js";

function Map(props) {
  const mapInfo = mapInfoSelectedRegion(TrimbleMaps.Common.Region.NA);
  const mapContainer = useRef(null);
  const { setMap, mapService, apiKey } = props;
  useEffect(() => {
    if (apiKey) {
      const mapInstance = mapService.initMap(
        {
          container: mapContainer.current,
          style: "transportation",
          center: mapInfo.center,
          zoom: mapInfo.zoom,
          hash: false,
          region: mapInfo.region,
        },
        apiKey
      );
      setMap(mapInstance);
    }
  }, [apiKey]);

  return <div className="map h-100" id="map" ref={mapContainer}></div>;
}

export default Map;
